### ISSUE TITLE
Error integrating vue-material

### ISSUE THREAD

**Issue by msantore** [davidroyer/nuxt-ssr-firebase#11]
I've added vue-material per these instructions: https://github.com/vuematerial/nuxtjs 

Here is my fork of your repo: https://github.com/msantore/nuxt-ssr-firebase
- I updated these packages for Firebase Node 8 support on /prod/server/package.json: 
    "firebase-admin": "5.13.1",
    "firebase-functions": "^2.0.2",

When I firebase serve locally, it works, vue-material isn't loading. 

When I deploy to Firebase, I get this error: 
<img width="1280" alt="screenshot 2018-07-27 09 02 34" src="https://user-images.githubusercontent.com/2057610/43331980-d380ad70-917b-11e8-92df-4e0de18c9953.png">

**Comment by WeAspireDev** [comment]
@msantore you got the fix for the issue?

**Comment by vari8** [comment]
I also have a similar issue. Do you guys @msantore @WeAspireDev @davidroyer already know how to fix it? Also, here is an error message that I got from my cloud function console:

```
{ Error: Cannot find module 'vue-material' from '/srv'
    at Function.resolveSync [as sync] (/srv/node_modules/resolve/lib/sync.js:81:15)
    at /srv/node_modules/vue-server-renderer/build.prod.js:1:77713
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:1053:18)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.<anonymous> (server-bundle.js:3491:71)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.<anonymous> (server-bundle.js:1374:92)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.<anonymous> (server-bundle.js:1072:65)
    at __webpack_require__ (server-bundle.js:27:30)
    at server-bundle.js:92:18
    at Object.<anonymous> (server-bundle.js:95:10)
    at o (/srv/node_modules/vue-server-renderer/build.prod.js:1:77607)
    at /srv/node_modules/vue-server-renderer/build.prod.js:1:78200
    at new Promise (<anonymous>)
    at /srv/node_modules/vue-server-renderer/build.prod.js:1:78108
  code: 'MODULE_NOT_FOUND',
  statusCode: 500,
  name: 'NuxtServerError' }
```

Please kindly let me know if anyone have a solution to this problem. Thanks in advance!
